Replace `cv2.Mat` type hints. Fuck you PyCharm.
Somehow, when running this package under PyCharm, it always errors out,
complaining `AttributeError: 'cv2' does not have attribute 'Mat'`. I
sunk 2 days into it, it blocked development, it drove me crazy. No
amount of Googling could do. Worst part: `python -m agf_toolkit` runs
fine. I then thought it had something to do with `runpy` because of the
traceback: Nope. And the cherry on top was that it could not be
replicated on a fresh repo with only `opencv-python` and
`opencv-contrib-python`.Here's the full traceback for whoever the poor
soul reading this commit:

Traceback (most recent call last):
  File "~\AppData\Local\Programs\Python\Python310\lib\runpy.py", L196
    return _run_code(code, main_globals, None,
  File "~\AppData\Local\Programs\Python\Python310\lib\runpy.py", L86
    exec(code, run_globals)
  File "D:\dev\agf-toolkit\agf_toolkit\__main__.py", L7
    from agf_toolkit.processor import gears, image, text
  File "D:\dev\agf-toolkit\agf_toolkit\processor\image.py", L8
    from agf_toolkit.utils import color
  File "D:\dev\agf-toolkit\agf_toolkit\utils\color.py", L13
    def get_rgb(bgr_image: cv2.Mat, coord_x: int, coord_y: int)...
AttributeError: module 'cv2' has no attribute 'Mat'

Type hints extracted from GitHub @ microsoft/python-type-stubs.